#change configfile to point to experiment_config.yaml for this experiment
#change mkdir, --output and --error to point to log folder for this experiment
#change mail-user, mail-type to point to your email
#can change default resources or set-resources as needed


snakefile: Snakefile.py
use-conda: True
conda-frontend: conda
rerun-incomplete: True
restart-times: 1
jobs: 400
latency-wait: 30
keep-going: True
configfile: ./experiment_info.yaml
conda-prefix: /nfs/tamilab001/c3ddb-scratch-mit_lieberman/tools/conda_snakemake
cluster-status: /nfs/tamilab001/c3ddb-scratch-mit_lieberman/scripts/slurm_status.py
reason: True
# dryrun: True
# unlock: True

cluster:
  mkdir -p ./logs/ &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.ntasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name="SM.{rule}"
    --output="./logs/%j_{rule}.out.txt"
    --error="./logs/%j_{rule}.err.txt"
    --exclude="node035,node390"
    --mail-user="YOUR_EMAIL_HERE"
    --mail-type="FAIL"


default-resources:
   - partition="sched_mit_tami"
   - time="1:00:00"
   - ntasks=1
   - cpus_per_task=1
   - mem=8000

set-resources:
   # make_data_links
   # antismash
   - antismash:mem=16000
   - antismash:cpus_per_task=4
   # concatentate_antismash_results
   - concatentate_antismash_results:partition="sched_any_quicktest"
   - concatentate_antismash_results:time="0:15:00"
   # bigscape
   - bigscape:cpus_per_task=4
   - bigscape:mem=16000
   # roary
   - roary:cpus_per_task=8
   - roary:mem=16000
   - roary:time="2:00:00"

